/usr/bin/env python $FINDER/flash_finder.py \
--x_units 'optvel' \
--y_units 'mJy' \
--out_path $FINDER'/examples/chains' \
--data_path $FINDER'/examples/data/' \
--nlive 500 \
--channel_function 'none' \
--channel_path $FINDER'/examples/data/hipass_channel.dat' \
--plot_restframe 'none' \
--noise_factor '1.00' \
--x0_sigma '200' \
--watch \
--verbose \
--param_out 'median' \
--mmodal \
--plot_switch \
